"""Public Part A calibration and semantic-state API."""

from .blink import (
    BlinkRateSnapshot,
    BlinkRateTracker,
    BlinkTrackerConfig,
    EyeState,
)
from .calibration import (
    CalibrationCollector,
    CalibrationConfig,
    CalibrationProfile,
    CalibrationProgress,
    CalibrationSampleCounts,
    CalibrationState,
)
from .annotations import (
    ANNOTATION_SCHEMA_NAME,
    ANNOTATION_SCHEMA_VERSION,
    AnnotationJsonFile,
    AnnotationLimits,
    AnnotationSet,
    AnnotationValidationError,
)
from .candidates import (
    CANDIDATE_SCHEMA_VERSION,
    PART_A_EVENT_NAMES,
    CandidateComponentContext,
    CandidateContext,
    CandidateJsonlFile,
    CandidateJsonlLimits,
    CandidateJsonlSummary,
    CandidateTransition,
    CandidateValidationError,
    ConfidenceEstimate,
    ConfidenceStatus,
    PartACandidateEmitter,
    PartAEventCandidate,
    candidate_context_sha256,
    candidate_from_mapping,
)
from .core import (
    ConditionState,
    SemanticState,
    TemporalPhase,
    TemporalStateConfig,
    TemporalStateMachine,
    TemporalStateSnapshot,
)
from .rules import (
    ErgonomicsEventConfig,
    ErgonomicsRuleEngine,
    ErgonomicsRuleSnapshot,
    RuleEvaluation,
)

__all__ = [
    "ANNOTATION_SCHEMA_NAME",
    "ANNOTATION_SCHEMA_VERSION",
    "AnnotationJsonFile",
    "AnnotationLimits",
    "AnnotationSet",
    "AnnotationValidationError",
    "BlinkRateSnapshot",
    "BlinkRateTracker",
    "BlinkTrackerConfig",
    "CalibrationCollector",
    "CalibrationConfig",
    "CalibrationProfile",
    "CalibrationProgress",
    "CalibrationSampleCounts",
    "CalibrationState",
    "CANDIDATE_SCHEMA_VERSION",
    "PART_A_EVENT_NAMES",
    "CandidateComponentContext",
    "CandidateContext",
    "CandidateJsonlFile",
    "CandidateJsonlLimits",
    "CandidateJsonlSummary",
    "CandidateTransition",
    "CandidateValidationError",
    "ConditionState",
    "ConfidenceEstimate",
    "ConfidenceStatus",
    "ErgonomicsEventConfig",
    "ErgonomicsRuleEngine",
    "ErgonomicsRuleSnapshot",
    "EyeState",
    "PartACandidateEmitter",
    "PartAEventCandidate",
    "RuleEvaluation",
    "SemanticState",
    "TemporalPhase",
    "TemporalStateConfig",
    "TemporalStateMachine",
    "TemporalStateSnapshot",
    "candidate_context_sha256",
    "candidate_from_mapping",
]
